src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp
He añadido mi enlace con el formato del título requerido.
Refs #6
=> Task 006: enlace de Curro añadido.

src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp
He añadido mi enlace con el formato del titulo requerido.
He tenido un problema de ramas asi que hago este merge para que la rama nombrada correctamente tenga los cambios.
Refs #5
=> Enlace Max añadido

src/main/java/acme/entities/airport/Airport.java, src/main/java/acme/entities/airport/OperationalScope.java
I have implemented the Airport Entity in addition to the OperationalScope Enumerate.
=> Task 010: Airport Entity - Group IR

src/main/java/acme/constraints/ValidPhone.java, src/main/java/acme/entities/airport/Airport.java, src/main/java/acme/entities/airport/OperationalScope.java
He realizado un reset de la anterior pull request, en la que implementaba la entidad Aeropuerto, ya que encontré varios errores y no se subieron bien los commits. Ahora está todo implementado, Airport, OperationalScope y ValidPhone
=> Task 010: Airport Entity-Group IR (2)

src/main/java/acme/constraints/ValidPhone.java, src/main/java/acme/entities/airline/Airline.java, src/main/java/acme/entities/airline/AirlineType.java
He creado la entidad Airline y un enumerado para su atributo "tipo" Refs #18
=> Task 011: airline entity

src/main/java/acme/realms/flightcrewmembers/AvailabilityStatus.java, src/main/java/acme/realms/flightcrewmembers/FlighCrewMember.java, src/main/java/acme/realms/flightcrewmembers/FlightCrewMember.java
He creado la entidad FlightCrewMembers.
Refs #30
=> Task 022: Flight Crew Members Entity D02-S3: Ir-1

src/main/java/acme/constraints/ValidText.java, src/main/java/acme/realms/Technician.java
He creado la clase Technician.java
Refs #38
=> Task 030: Student 5 - First IR

src/main/java/acme/entities/aircraft/Aircraft.java, src/main/java/acme/entities/aircraft/ServiceStatus.java
He creado la entidad Aircraft con el enumerate ServiceStatus.
Refs #61
=> Task 045: Aircraft entity

src/main/java/acme/realms/AssistanceAgent.java
He creado la entidad assistanceAgent.
Refs #34
=> Task 26: Assistance Agent Entity

src/main/java/acme/entities/Service.java
He creado la entidad service especificada en los requisitos grupales.
refs #19
=> Task 12: Creada la entidad service.

src/main/java/acme/entities/claim/Claim.java, src/main/java/acme/entities/claim/ClaimType.java, src/main/java/acme/realms/AssistanceAgent.java
He creado la entidad Claim.
Refs #35
=> Task 027: student 4  second ir

src/main/java/acme/entities/trackingLog/TrackingLog.java
=> Creada la entidad Tracking Log

src/main/java/acme/realms/AssistanceAgent.java, src/main/resources/WEB-INF/data/sample/airline.csv, src/main/resources/WEB-INF/data/sample/assistanceAgent.csv, src/main/resources/WEB-INF/data/sample/user-account.csv
He creado un archivo de csv para introducir los datos de 2 agentes y
otro archivo para crear una aereolinea necesaria para la relación con
airline. Además he hecho un pequeño arreglo en la clase AssistanceAgent
en un tipo de dato.
Refs #37
=> task 029 student 4 first tr

src/main/java/acme/entities/flight/Flight.java, src/main/java/acme/entities/flight/FlightRepository.java
He creado la entidad Flight y su repositorio para los atributos derivados.
Refs #23
=> Task 016: Flight entity.

src/main/java/acme/entities/flight/Leg.java, src/main/java/acme/entities/flight/LegStatus.java
He creado la entidad Leg, junto con su enumerado para el atributo Status.
=> Task 017: Leg entity

src/main/java/acme/entities/flightassignment/AssignmentStatus.java, src/main/java/acme/entities/flightassignment/Duty.java, src/main/java/acme/entities/flightassignment/FlightAssignment.java
Añadida la implementación de FlightAssignment
=> Task 023: Flight Assignment Entity D02-S3: Ir 2

src/main/java/acme/constraints/ValidText.java, src/main/java/acme/entities/activitylog/ActivityLog.java
Añadida la entidad Activity Log
=> Task 024: Activity Log Entity D02-S3: IR3

reports/Student #3/UML Domain Model/S3-entities.uxf, reports/Student #3/UML Domain Model/S3-realms.uxf
He subido el diagrama de entities y realms del estudiante 3.
Refs #52
=> Task 041:  S3 - Class Diagrams

src/main/java/acme/constraints/ValidEmployeeIdentifier.java, src/main/java/acme/constraints/ValidFlightNumberDigits.java, src/main/java/acme/constraints/ValidIataCode.java, src/main/java/acme/constraints/ValidManagerIdentifier.java, src/main/java/acme/constraints/ValidShortText.java, src/main/java/acme/constraints/ValidText.java, src/main/java/acme/constraints/ValidYearsOfExperience.java, src/main/java/acme/entities/airline/Airline.java, src/main/java/acme/entities/flight/Flight.java, src/main/java/acme/entities/flight/Leg.java, src/main/java/acme/realms/Manager.java
He creado las validaciones necesarias para las entidades a crear por el estudiante 1.
=> Task 47: Refs #82 Creación de validaciones (estudiante 1)

reports/Domain-model/D02-S1-realms.uxf, reports/Student #1/Domain-model/D02-S1-realms.uxf
He creado el diagrama de clases de los roles a crear por el estudiante 1.
Refs #47
=> Doc: Upload realms diagram D02-S1

src/main/java/acme/entities/purchase/Purchase.java, src/main/java/acme/realms/Customer.java
He creado el rol Customer Refs
#26
=> Task 019: Creación de la entidad Customer

reports/Student #2/Domain-model/D02-S2-entities.uxf, reports/Student #2/Domain-model/D02-S2-realms.uxf, src/main/java/acme/entities/activitylog/ActivityLog.java, src/main/java/acme/entities/booking/Booking.java, src/main/java/acme/entities/booking/BookingRecord.java, src/main/java/acme/entities/purchase/Purchase.java, src/main/java/acme/realms/Customer.java
He cambiado la relación entre customer y purchase, he implementado las validaciones nuevas, he hecho imports que faltaban y he corregido el diagrama de dominio
Refs #88
=> Fix Customer y imports.

src/main/resources/WEB-INF/data/sample/manager.csv, src/main/resources/WEB-INF/data/sample/user-account.csv
=> Task 018: test S01-sample data for manager entity

reports/Student #2/Domain-model/D02-S2-entities.uxf, src/main/java/acme/constraints/ValidLastNibble.java, src/main/java/acme/constraints/ValidLocatorCode.java, src/main/java/acme/entities/booking/Booking.java, src/main/java/acme/entities/booking/BookingRecord.java
He cambiado las validaciones de Booking, BookingRecord y la parte del diagrama de dominio correspondiente.
Refs #91
=> Fix Booking

reports/Student #2/Domain-model/D02-S2-entities.uxf, src/main/java/acme/constraints/ValidPassportNumber.java, src/main/java/acme/entities/passenger/Passenger.java
He cambiado las validaciones de la entidad Passenger y he corregido el diagrama de dominio correspondiente.
Refs #94
=> Fix Passenger

src/main/java/acme/realms/Manager.java
=> Fix: añadir relación entre Manager y Airline

src/main/java/acme/constraints/ValidSecurityLevel.java, src/main/java/acme/entities/activitylog/ActivityLog.java
=> Task 024/R1: Review Activity Log.

reports/Group/UML Domain Model/datatypes.uxf
=> Task 036: Datatypes Diagram

src/main/resources/WEB-INF/data/sample/aircraft.csv, src/main/resources/WEB-INF/data/sample/airline.csv, src/main/resources/WEB-INF/data/sample/assistanceAgent.csv, src/main/resources/WEB-INF/data/sample/flight.csv, src/main/resources/WEB-INF/data/sample/leg.csv, src/main/resources/WEB-INF/data/sample/manager.csv, src/main/resources/WEB-INF/data/sample/user-account.csv
=> Task 018/R1: sample data para Airline, Flight y Leg

src/main/resources/WEB-INF/data/sample/activity-log.csv, src/main/resources/WEB-INF/data/sample/flight-assignment.csv
=> Task 025/R1: Review Sample Data Student 3

src/main/java/acme/constraints/MaintenanceRecordValidator.java, src/main/java/acme/constraints/ValidMaintenanceRecord.java, src/main/java/acme/entities/maintenanceRecord/MaintenanceRecord.java, src/main/java/acme/entities/maintenanceRecord/MaintenanceRecordStatus.java
He creado correctamente la entidad MaintenanceRecords.
Refs #39
=> Task 031: Student 5 - Maintenance records

src/main/java/acme/entities/review/Review.java
He creado la entidad review de los requisitos grupales.
Refs #20
=> Task 013: Review entity - Group IR

src/main/java/acme/entities/task/Involves.java, src/main/java/acme/entities/task/Task.java, src/main/java/acme/entities/task/TaskType.java
He creado la entidad task adecuadamente.
Refs #40
=> Task 032: Student 5 - Tasks

src/main/java/acme/constraints/ValidCargoWeight.java, src/main/java/acme/entities/aircraft/Aircraft.java
He corregido las validaciones de la entidad Aircraft.
Refs #97
=> Fix Aircraft

src/main/resources/WEB-INF/data/sample/booking.csv, src/main/resources/WEB-INF/data/sample/bookingRecord.csv, src/main/resources/WEB-INF/data/sample/customer.csv, src/main/resources/WEB-INF/data/sample/passenger.csv, src/main/resources/WEB-INF/data/sample/user-account.csv
He añadido los ficheros de pruebas para las entidades booking, bookingRecord, passenger y el rol customer. También he creado las cuentas para los customers.
Refs #29
=> Task 034: First testing requirements

reports/Student #5/UML Domain Model/D02-S5-entities.uxf, reports/Student #5/UML Domain Model/D02-S5-realms.uxf
He creado los diagramas para las entidades y realms previamente creados en el entregable 2.
Refs #54
=> Task 43 class diagrams student 5

reports/Student #4/Domain-model/D02-S4-Diagram.uxf
=> Añadido diagrama de entidades S4

src/main/resources/WEB-INF/data/sample/aircraft.csv
He cambiado algunos valores que hacían que la aplicación fallaba.
Refs #124
=> Fix data initial

src/main/java/acme/entities/service/Service.java, src/main/resources/WEB-INF/data/sample/service.csv
He añadido los datos de prueba de la clase Service.
Refs #126
=> Service Data

src/main/resources/WEB-INF/data/sample/involves.csv, src/main/resources/WEB-INF/data/sample/maintenance-record.csv, src/main/resources/WEB-INF/data/sample/task.csv, src/main/resources/WEB-INF/data/sample/technician.csv, src/main/resources/WEB-INF/data/sample/user-account.csv
Student 5 Entities Sample Data
Refs #41
=> Task 033: Student 5 - First TR

src/main/java/acme/entities/claim/Claim.java, src/main/java/acme/entities/claim/ClaimStatus.java, src/main/java/acme/entities/tracking_log/TrackingLog.java, src/main/java/acme/features/assistanceAgent/claim/ClaimController.java, src/main/java/acme/features/assistanceAgent/claim/ClaimCreateService.java, src/main/java/acme/features/assistanceAgent/claim/ClaimDeleteService.java, src/main/java/acme/features/assistanceAgent/claim/ClaimPublishService.java, src/main/java/acme/features/assistanceAgent/claim/ClaimRepository.java, src/main/java/acme/features/assistanceAgent/claim/ClaimShowService.java, src/main/java/acme/features/assistanceAgent/claim/ClaimUpdateService.java, src/main/java/acme/features/assistanceAgent/claim/CompletedClaimListService.java, src/main/java/acme/features/assistanceAgent/claim/PendingClaimListService.java, src/main/java/acme/realms/AssistanceAgent.java, src/main/resources/WEB-INF/data/sample/assistanceAgent.csv, src/main/resources/WEB-INF/data/sample/claim.csv, src/main/resources/WEB-INF/data/sample/tracking-log.csv, src/main/resources/WEB-INF/views/assistance-agent/claim/form.jsp, src/main/resources/WEB-INF/views/assistance-agent/claim/list.jsp, src/main/resources/WEB-INF/views/assistance-agent/claim/messages-en.i18n, src/main/resources/WEB-INF/views/assistance-agent/claim/messages-es.i18n, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp
He creado la funcionalidad para que un agente pueda listar, actualizar, crear, publicar y eliminar sus reclamaciones.
Refs #139
=> Operaciones de Agentes en las reclamaciones

src/main/java/acme/constraints/ValidSeverityLevel.java, src/main/java/acme/entities/activitylog/ActivityLog.java, src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogController.java, src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogCreateService.java, src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogDeleteService.java, src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogListService.java, src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogPublishService.java, src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogRepository.java, src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogShowService.java, src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogUpdateService.java, src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberAssignmentController.java, src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberAssignmentListCompletedService.java, src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberAssignmentListPlannedService.java, src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberAssignmentRepository.java, src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberAssignmentUpdateService.java, src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentCreateService.java, src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentDeleteService.java, src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentShowService.java, src/main/resources/WEB-INF/data/sample/activity-log.csv, src/main/resources/WEB-INF/views/flight-crew-member/activity-log/form.jsp, src/main/resources/WEB-INF/views/flight-crew-member/activity-log/list.jsp, src/main/resources/WEB-INF/views/flight-crew-member/activity-log/messages-en.i18n, src/main/resources/WEB-INF/views/flight-crew-member/activity-log/messages-es.i18n
Flight crew member operations on Activity logs
=> Student 3 task 009 flight crew member operations on activity logs

src/main/java/acme/features/customer/passenger/CustomerPassengerController.java, src/main/java/acme/features/customer/passenger/CustomerPassengerCreateService.java, src/main/java/acme/features/customer/passenger/CustomerPassengerListService.java, src/main/java/acme/features/customer/passenger/CustomerPassengerPublishService.java, src/main/java/acme/features/customer/passenger/CustomerPassengerRepository.java, src/main/java/acme/features/customer/passenger/CustomerPassengerShowService.java, src/main/java/acme/features/customer/passenger/CustomerPassengerUpdateService.java, src/main/resources/WEB-INF/views/customer/passenger/form.jsp, src/main/resources/WEB-INF/views/customer/passenger/list.jsp, src/main/resources/WEB-INF/views/customer/passenger/messages-en.i18n, src/main/resources/WEB-INF/views/customer/passenger/messages-es.i18n
=> Customer operations on passengers
